// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PowerTestResult {
    "action": string;
    "success": boolean;
    "message": string;
    "timestamp": string;

    /** Creates a new PowerTestResult instance. */
    constructor($$source: Partial<PowerTestResult> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PowerTestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PowerTestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PowerTestResult($$parsedSource as Partial<PowerTestResult>);
    }
}
